StdReads:
    rawReads1: /mnt/nfs/gigantor/ifs/DCEG/CGF/Resources/PacBio/jobs/cromwell-executions/pb_ccs/df027b98-f0cb-40e8-88d3-cbcb7e14443f/call-consolidate_reads_bam/execution/reads.bam
    rawReads2: /mnt/nfs/gigantor/ifs/DCEG/CGF/Resources/PacBio/jobs/cromwell-executions/pb_ccs/2185085a-5312-4b77-ac11-18a44e602639/call-consolidate_reads_bam/execution/reads.bam
    rawReads3: /mnt/nfs/gigantor/ifs/DCEG/CGF/Resources/PacBio/jobs/cromwell-executions/pb_ccs/da8bc6a1-9f77-4760-96fd-c9cb12eda776/call-consolidate_reads_bam/execution/reads.bam

UltraLowReads:
    rawReads1: /mnt/nfs/gigantor/ifs/DCEG/CGF/Resources/PacBio/jobs/cromwell-executions/pb_ccs/341761d4-1149-4c7d-835d-50c6e029f705/call-consolidate_reads_bam/execution/reads.bam    
    rawReads2: /mnt/nfs/gigantor/ifs/DCEG/CGF/Resources/PacBio/jobs/cromwell-executions/pb_ccs/7e530225-aa8e-4acd-a5c1-25ce2ff14596/call-consolidate_reads_bam/execution/reads.bam
    rawReads3: /mnt/nfs/gigantor/ifs/DCEG/CGF/Resources/PacBio/jobs/cromwell-executions/pb_ccs/bdacfa7f-7f06-452c-95c0-286784b1eb4d/call-consolidate_reads_bam/execution/reads.bam
    rawReads4: /mnt/nfs/gigantor/ifs/DCEG/CGF/Resources/PacBio/jobs/cromwell-executions/pb_ccs/b5c68b9c-314a-4c46-af4f-7cc2a2f85b22/call-consolidate_reads_bam/execution/reads.bam    

GeneralInfo:
    ref: /scratch/lix33/Data/Reference/v37/hg19_canonical+phiX.fa
    bamDir: /CGF/Bioinformatics/Production/Wen/20200117_pacbio_snp_call/29461_WGS_cell_line/bam_bemchmark
    svDir: /CGF/Bioinformatics/Production/Wen/20200117_pacbio_snp_call/29461_WGS_cell_line/bam_bemchmark/SV
    tr_bed: ../../Configs/human_hs37d5.trf.bed

sniffles:
    minSupport: 10,5
    
cuteSV:
    minSupport: 10,5
    
pbsv:    
    minReads: 1,5
    
    