General:
    ref : /DCEG/CGF/TempFileSwap/Kristie/References/GRCh38.p2.maimcontigs.fa    
    tr_bed: /CGF/Bioinformatics/Production/Wen/20200117_pacbio_snp_call/29461_WGS_cell_line/SV/Mila/Dependence/human_GRCh38_no_alt_analysis_set.trf.bed
    buildDir: /scratch/lix33/Test/Pacbio/StdPipeline/Data
    
Customized:
    readsList: /scratch/lix33/Test/NanoPlot/readslist.csv    
    
sniffles:
    minSupport: 5
    
cuteSV:
    minSupport: 5
    
pbsv:    
    minReads: 5