include: "rule_A"
include: "rule_B"
include: "rule_C"
include: "rule_SUM"


rule all:
    input:
        "Output/OutputA.txt",
        "Output/OutputB.txt",
        "Output/OutputC.txt",
        "Output/Sum.txt"

